
// This file has been generated by the GUI designer. Do not modify.

public partial class frmMain
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action dialogInfoAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menuMain;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Notebook noteMain;
	
	private global::Gtk.Label lblPageHome;
	
	private global::Gtk.Label lblPageApplications;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView txtConsole;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnClean;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Button btnClear;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget frmMain
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.HelpAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
		w1.Add (this.dialogInfoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "frmMain";
		this.Title = global::Mono.Unix.Catalog.GetString ("Linux Deletion Utility");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		this.DefaultWidth = 600;
		this.DefaultHeight = 400;
		// Container child frmMain.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menuMain'><menu name='HelpAction' action='HelpAction'><menuitem name='dialogInfoAction' action='dialogInfoAction'/></menu></menubar></ui>");
		this.menuMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menuMain")));
		this.menuMain.Name = "menuMain";
		this.vbox1.Add (this.menuMain);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menuMain]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.noteMain = new global::Gtk.Notebook ();
		this.noteMain.CanFocus = true;
		this.noteMain.Name = "noteMain";
		this.noteMain.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w3 = new global::Gtk.Label ();
		w3.Visible = true;
		this.noteMain.Add (w3);
		this.lblPageHome = new global::Gtk.Label ();
		this.lblPageHome.Name = "lblPageHome";
		this.lblPageHome.LabelProp = global::Mono.Unix.Catalog.GetString ("Home Folder");
		this.noteMain.SetTabLabel (w3, this.lblPageHome);
		this.lblPageHome.ShowAll ();
		// Notebook tab
		global::Gtk.Label w4 = new global::Gtk.Label ();
		w4.Visible = true;
		this.noteMain.Add (w4);
		this.lblPageApplications = new global::Gtk.Label ();
		this.lblPageApplications.Name = "lblPageApplications";
		this.lblPageApplications.LabelProp = global::Mono.Unix.Catalog.GetString ("Applications");
		this.noteMain.SetTabLabel (w4, this.lblPageApplications);
		this.lblPageApplications.ShowAll ();
		this.hbox2.Add (this.noteMain);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.noteMain]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtConsole = new global::Gtk.TextView ();
		this.txtConsole.CanFocus = true;
		this.txtConsole.Name = "txtConsole";
		this.txtConsole.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add (this.txtConsole);
		this.hbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
		w7.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnClean = new global::Gtk.Button ();
		this.btnClean.CanFocus = true;
		this.btnClean.Name = "btnClean";
		this.btnClean.UseUnderline = true;
		this.btnClean.Label = global::Mono.Unix.Catalog.GetString ("_Start Cleaning");
		this.hbox1.Add (this.btnClean);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnClean]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.hbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator1]));
		w10.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnClear = new global::Gtk.Button ();
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("_Clear Selection");
		this.hbox1.Add (this.btnClear);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnClear]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.menuAbout_Click);
	}
}
